### ISSUE TITLE
Home - Mobile Images need updating

### ISSUE THREAD

**Issue by ckillorin** [designbyparker/ModernShed#104]
All of the hero carousel images need to be swapped.

**Comment by eidetyler** [comment]
I think these images are working well for now. I don't see anything missing.

**Comment by ckillorin** [comment]
I'm confused. Yesterday you said these were not MS images. I'm pretty sure at least some of them are from competitors. Can you take another look?
![Screen Shot 2020-03-31 at 7 51 01 PM](https://user-images.githubusercontent.com/60364092/78094257-f5837100-7388-11ea-98b3-d82c24690aef.png)

**Comment by eidetyler** [comment]
I mistook two bugs for each other - I wrote comments to this one in another thread. These are done and in DB.
