### ISSUE TITLE
Global - Line Spacing (Body Copy)

### ISSUE THREAD

**Issue by eidetyler** [designbyparker/ModernShed#114]
Can we increase the line spacing on body copy? I know it'll make them even longer, but it's pretty crammed. Attached Image.

Example:
![Screen Shot 2020-04-03 at 2 57 01 PM](https://user-images.githubusercontent.com/60489677/78408218-60b48980-75bb-11ea-92e6-933543d99760.png)

**Comment by CaityHeath** [comment]
We can update line-height, not sure I know exactly what you mean by body copy tho. The line-height on both descriptive columns? Or just the far right column?

**Comment by CaityHeath** [comment]
We can update line-height however, it's going to be a big lif if you want it truly global. I'll need more direction before I proceed with the change, like line-height spacing right now the line height for paragraph text is 22px and font size is 19px.
