### ISSUE TITLE
Hero Content : Copy needs to be trimmed

### ISSUE THREAD

**Issue by CaityHeath** [designbyparker/ModernShed#115]
Hero copy word count is too inconsistent.  On Sheds its 9 words long and on Our Story it is 28 words long. I cannot achieve the design for mobile. 
Our Story Mobile iphone 6/7/8
![Screen Shot 2020-04-04 at 1 04 22 PM](https://user-images.githubusercontent.com/37593478/78460451-c36a5b80-7675-11ea-82f2-338af9c781a9.png)
Our Story Mobile iphone 6/7/8
![Screen Shot 2020-04-04 at 1 12 11 PM](https://user-images.githubusercontent.com/37593478/78460472-f01e7300-7675-11ea-9d96-5e3af661b93f.png)
Design 
![Screen Shot 2020-04-04 at 1 13 45 PM](https://user-images.githubusercontent.com/37593478/78460505-25c35c00-7676-11ea-801e-11fc78c05a8d.png)

**Comment by ckillorin** [comment]
For some reason, I'm getting a 404 error on all of those screenshots. Since the length is similar for Our Story and Process, would it be easiest to increase the word count for Sheds? Let me know and I can get Britt on a copy tweak.
