### ISSUE TITLE
Sheds - Animated Gif Positioning

### ISSUE THREAD

**Issue by eidetyler** [designbyparker/ModernShed#130]
Question. Can we cheat this animated gif UP to be up against the yellow header area? Since the text is animating, it sits low in relation to it's image on the left. 

Close or comment if this isn't doable.

![Screen Shot 2020-04-07 at 9 16 10 AM](https://user-images.githubusercontent.com/60489677/78693742-8807a100-78b0-11ea-87a1-eb1ea6e33565.png)

**Comment by CaityHeath** [comment]
I don't want to do that because it will break the borderline on the left side. It would be easier to make a new gif than cheat the grid
