### ISSUE TITLE
Mobile - Contact Form Button Selection

### ISSUE THREAD

**Issue by eidetyler** [designbyparker/ModernShed#135]
Need to make the entire field a touch-target on mobile. Looks like the radio buttons and text are acting as independent buttons. 

![IMG_5462](https://user-images.githubusercontent.com/60489677/78719398-b600db80-78d8-11ea-9b34-60c70b7e2a8c.jpg)

**Comment by CaityHeath** [comment]
I can't replicate the image you produced on chrome or safari. Which browser are you using? This bug is going to take some time to figure out
