### ISSUE TITLE
Home, navigation-logo

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#142]
Edge, Feature. 
Very difficult to see logo and navigation text over top of photos. 
Suggest transparent band behind text?

**Comment by eidetyler** [comment]
Images are updated @CaityHeath in DB.

**Comment by CaityHeath** [comment]
@eidetyler We still need an updated version of image #1, the sauna and storage shed. This info is pulling from the database so if you want it removed it needs to be updated there first. Otherwise, we need all four images as we had before
