### ISSUE TITLE
Home-main hero photos

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#143]
Edge, desktop, Content. 
Description of photo (label at bottom of photo) doesn't change when photo changes. I realize this is probably pulled form the DB? or you just need descriptions from us for each one?

**Comment by ckillorin** [comment]
@ModernShed Yep! This is pulled from the database. We'll need the following info:

- square footage

- neighborhood

- city, state

- use

**Comment by ckillorin** [comment]
@ModernShed we'll also need these details for the home carousel so that Monte can add to the database
