### ISSUE TITLE
Our Story - Team Photos missing

### ISSUE THREAD

**Issue by ckillorin** [designbyparker/ModernShed#145]
Tim realized that he forgot to give us a couple of team photos so he shared those w me yesterday. Embedding links to the original assets for cropping and whatnot.

[Gregg - Sales Rep](https://www.dropbox.com/s/zhj6fgwsexggtf8/Gregg-Probach-sales%20rep.jpg?dl=0)
[Jim - Draftsman](https://www.dropbox.com/s/ne31lbydwciw9ok/JIM-DRAFTSMAN.jpg?dl=0)

**Comment by CaityHeath** [comment]
The backend has been updated and front end is pulling a place holder photo for Gregg and Jim as photos still need to be edited

@eidetyler reassigning this bug to you because all that's left are photo edits

**Comment by eidetyler** [comment]
Images are here - as good as Gregs is going to get.

@CaityHeath 

![Greg](https://user-images.githubusercontent.com/60489677/79507289-55fee900-7fec-11ea-9d9f-5936db6cd75b.png)
![Jim](https://user-images.githubusercontent.com/60489677/79507299-5b5c3380-7fec-11ea-90e8-1c85df9f829d.png)

**Comment by CaityHeath** [comment]
Looks great!
