### ISSUE TITLE
Weird line on photograpch

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#148]
Featured sheds page:
upshot photo of shed in upper rt quad has a line in it that isn't in the other exact same photo. Looks like a hair or branch.. It is in the sky portion of the pic
![image](https://user-images.githubusercontent.com/63302981/79137908-70c12b80-7d68-11ea-8ffa-f70133b78df6.png)

**Comment by eidetyler** [comment]
Fixed. In DB.

https://www.dropbox.com/s/52t8nwi1iw5i39p/01.jpg?dl=0

**Comment by ModernShed** [comment]
I am away from my office/desk for the remainder of the day today, Thursday, April 16th. I will be back at my desk tomorrow at 8am.

GM
Tim Vack
Modern-Shed, Inc.
