### ISSUE TITLE
Sheds page: Feature and or bug" Browse more..

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#150]
The text says "…or browse more."
However, there is no  link to more shed imagery

**Comment by CaityHeath** [comment]
Note: I believe this is the copy on the Contact form CTA that is on the Home, Sheds and Process pages

**Comment by ckillorin** [comment]
@CaityHeath and @eidetyler I believe the issue is that "browse more" suggested to them that there should be a link to click. (perhaps to the Sheds page?) If that wasn't our intent, I'll flag this back to rework copy so it's more clear.

**Comment by ModernShed** [comment]
Maybe it should link to our current gallery at this point?

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by ckillorin** [comment]
@ModernShed our intent here is to drive traffic to the contact page. We'll revise the copy to make it more clear.

**Comment by ckillorin** [comment]
@CaityHeath copy should read "Get in contact with our team."
