### ISSUE TITLE
Content: Materials photos

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#151]
Most all photos aren't very good.
We don’t offer the siding depicted in the Metal and Painted Siding photo.
The text is inaccurate also. I will have to come up with the text and find better photos.. But the ones on our current site are better

**Comment by ckillorin** [comment]
@ModernShed 

Can you provide images for materials? We never got anything from you so either pulled close crops from your sheds or similar, higher quality images from royalty-free repositories.

**Comment by ModernShed** [comment]
Yes, I will get you images and text as soon as possible.. will try for tomorrow. If nothing else we’ll use what’s on our current site.

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by eidetyler** [comment]
@CaityHeath @ModernShed - Images are updated based on the 4 material types. So let's also update the text for each. The colors and details of each feel really nice together. 

1) Cedar Siding
2) Metal Siding
3) Open Joint Siding
4) Lap Siding

https://www.dropbox.com/sh/zb4bjn8n444ucua/AABeXZhDoEcW6lGs2XONgkHHa?dl=0

**Comment by ModernShed** [comment]
The lap siding is incorrect. It shows a wood grain at an 8” reveal. We don’t use that. We use a smooth face at a 10” reveal.. the problem is I am unsure if we have a straight on shot as an example. And the metal example is really dark.. can’t really tell what it is. Let me see if I can find a better shot.

 

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by eidetyler** [comment]
Updated the same link. These seem like they're working better. The lap siding is a MS image. 

https://www.dropbox.com/sh/zb4bjn8n444ucua/AABeXZhDoEcW6lGs2XONgkHHa?dl=0

**Comment by ckillorin** [comment]
@eidetyler Tim provided a couple better lit, more direct shots of the metal and lap siding. Let's see if these solve some of the issues with the darkness?
![az150123-198](https://user-images.githubusercontent.com/60364092/79355420-7a769a80-7ef2-11ea-8306-25c05bafacbe.jpg)
![Uploading DSC_2678.JPG…]()

**Comment by eidetyler** [comment]
Those worked well, thanks for sending @ModernShed Tim. These should do the trick then.

https://www.dropbox.com/sh/zb4bjn8n444ucua/AABeXZhDoEcW6lGs2XONgkHHa?dl=0
