### ISSUE TITLE
Content: Sheds: Windows: main body text

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#153]
Windows-main text. 
Let's change it to:
"Modern-Shed's are light and airy even with few windows due to the unique transom windows below the roof line. However, we offer a huge variety of window sizes, materials and styles for every budget and style and to let the light shine in even more." 
The labels aren't accurate.. windows aren't referred to as small tall and full but rather by style. Change to: Opening, Combination, Picture
Change text on right top photo to: "in squares and rectangles, opening windows can be had as awnings, sliding or casements"
Change text for middle picture to: "Fixed over awning, fixed under awning, fixed under sliding, fixed over sliding.... the combinations are almost endless.."
Change text for bottom picture to: "Let hte outdoors in with most any size picture windows whether small or large"

![image](https://user-images.githubusercontent.com/63302981/79138596-9f8bd180-7d69-11ea-8334-1535ba74940c.png)

**Comment by ckillorin** [comment]
@CaityHeath updated copy for both section body + different sizes located in our copy doc.
