### ISSUE TITLE
Content: Photos: Team

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#155]
I think you know about this arleady.. but..
Team photos are TOO BIG. And be sure to include everyone.
Please include only each person's 1st name.

**Comment by CaityHeath** [comment]
@ModernShed I'd just like a little clarification on this issue. Do you find the images to be too large on Desktop specifically? Or are they also too large on Tablet and Mobile?

I'll send a request to Monte today to make a database update to include Jim & Gregg and to remove last names.

**Comment by ModernShed** [comment]
They are huge on my desktop external monitors, on my Surface 13” screen. Each pic is 3-1/2”x4-3/4”

On my Android phone the pics are 1-5/8”x2-1/4” which gives one photo nicely centered left to right and up and down and is less than half the size on my computer screen. If the size they display on my phone, were the size displayed on the computer, that would probably be ok.. 

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com
