### ISSUE TITLE
Content: Our team: word change:

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#160]
Beginning paragraph: Change the word "home" to something else.. I would say "space" but that would have that word 2x in the same paragraph.. maybe you could come up with something else... but we don't want to impress the user that we design "homes".. we design studios and backyard rooms etc..I think the words "studios and ADUs" might be appropriate. 
![MSWEBQA-9](https://user-images.githubusercontent.com/63302981/79140024-33f73380-7d6c-11ea-859d-b98dc099f843.jpg)

**Comment by ckillorin** [comment]
@eidetyler I tagged you on the updated copy from Britt in our copy doc.

**Comment by ckillorin** [comment]
@CaityHeath @eidetyler this is addressed in the update associated with issue #161 

I'm going to move this to Caity to close.
