### ISSUE TITLE
Feature/Content: Our Story: Content

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#161]
There isn't much of a "story" here. I know you were waiting for a timeline from Ryan, but let's at least put some text from the current site under "our story" at the top.. So it is "our story" then lower, "our team"

**Comment by ckillorin** [comment]
@eidetyler I tagged you in the updated copy on our copy doc.

**Comment by eidetyler** [comment]
@CaityHeath Updated Illustrator file and .JPGS for reference are attached via the links. 

JPGS: https://www.dropbox.com/sh/xs7u7b461tv77nu/AACWTslfQRdMU-BqvpL3H8cWa?dl=0
Illustrator: https://www.dropbox.com/s/1h4kqbly3e5n31k/ModernShed_OurStory_Update.ai?dl=0

**Comment by ModernShed** [comment]
Looks good

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com
