### ISSUE TITLE
Bug: Our Story: below team photos link

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#162]
text "Interested in a shed?... Or browse more."
There is no link for "browse more"
![MSWEBQA-10](https://user-images.githubusercontent.com/63302981/79140479-e929eb80-7d6c-11ea-91de-67f2d6c7efe8.jpg)

**Comment by ckillorin** [comment]
@ModernShed the intent here is to drive the user to get in contact. We'll revise copy to be a bit more clear!

**Comment by ckillorin** [comment]
@CaityHeath copy should read: "Get in contact with our team."
