### ISSUE TITLE
Bug?/Feature: Scrolling of Team photos:

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#163]
The arrow, looks like the home page photo arrow but acts differently.. It doesn't float
Also the arrow doesn't scroll left and right, only  right then when at the end, the scoll auto bounces back to the left

![MSWEBQA-11](https://user-images.githubusercontent.com/63302981/79140979-c0562600-7d6d-11ea-839f-66be7fdb4bf2.jpg)

**Comment by ckillorin** [comment]
@ModernShed the arrow doesn't float because, with the black + white photos and a black or white arrow, there is a big contrast/visibility issue with a floating arrow. 

We can add an arrow on the left side to scroll back if that helps solve the usability issue you're seeing.

**Comment by ModernShed** [comment]
Yes, create a an arrow for both directions.. thanks!
