### ISSUE TITLE
Content: Photo image: Process: Step 01

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#164]
Change the photo from a stock photo to one of our people. We can get this to you this week

![MSWEBQA-12](https://user-images.githubusercontent.com/63302981/79141204-29d63480-7d6e-11ea-9364-9eeb90b1eb09.jpg)

**Comment by ckillorin** [comment]
@eidetyler please replace with this photo: https://www.dropbox.com/s/10qeua9bo7n0k8z/20200414_131143.jpg?dl=0
![20200414_131143](https://user-images.githubusercontent.com/60364092/79270879-c1618300-7e53-11ea-967e-da1023d82a0f.jpg)

**Comment by ModernShed** [comment]
Feel free to crop as you need.

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com
