### ISSUE TITLE
Content: Process: Step 02

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#165]
Change Step 02 Order picture- will send or attach or share
![image](https://user-images.githubusercontent.com/63302981/79141801-550d5380-7d6f-11ea-8889-d6b421f64bb2.png)

Change Step 03 Fabricate photo- will send or attach or share
![image](https://user-images.githubusercontent.com/63302981/79141822-60607f00-7d6f-11ea-8512-c59a8bc1f566.png)

Change Step 03 Intall photo-will send or attach or share.. 
![image](https://user-images.githubusercontent.com/63302981/79141834-68b8ba00-7d6f-11ea-9311-ffe81d5e81ec.png)

**Comment by ckillorin** [comment]
@ModernShed - we've used the photos you originally provided when we finalized content (with the exception of the first one which we can update when you provide a different one today - I'll also comment on that issue specifically). 

If you want us to use alternate images we can address those as hot-fix items post-launch and either set up an hourly rate or a maintenance retainer.

**Comment by ModernShed** [comment]
Ok.. only thing is, the “Fabricate” one I sent you was just taken a week ago and is much better showcasing fabrication than the loaded trailer.. but if we can’t swap it out, that is ok for now. I am hoping to get the Step 01 design pic very soon.. he is just swamped busy right now.

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by ckillorin** [comment]
@ModernShed we've updated the step 1 photo but won't be able to update the others before tomorrow. I'll keep this open to be addressed later on!

**Comment by ckillorin** [comment]
@CaityHeath removing tyler because we are not addressing this for launch.
