### ISSUE TITLE
Content: photo copy change: Difference page

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#167]
The Difference:
Picture for "A" needs to be a photo of typical site construction, not our plant. Let's choose a different pic for "B". And for B Insert this text before the 1st sentence. "All Modern-Sheds are built to IBC (international building code) and can easily be modified to stricter CBC (California building code) standards."
--Also, I don't like the unevenness of the photos.. I think they should be flush
![MSWEBQA-13](https://user-images.githubusercontent.com/63302981/79154686-d4f1e880-7d84-11ea-862b-3265ebaf149e.jpg)

**Comment by eidetyler** [comment]
@CaityHeath Image updated

https://www.dropbox.com/s/gvochis6hccx7h2/G_ModernShed_TheDifference_A.jpg?dl=0

**Comment by ModernShed** [comment]
Ummm.. this image is of a larger commercial construction site.. can you find an image of a residential construction site, please. Thanks.

**Comment by ckillorin** [comment]
@ModernShed

**Comment by ckillorin** [comment]
@eidetyler we need to swap one final image. See attached.

After this we are wrapped for this build.
![Typical -A](https://user-images.githubusercontent.com/60364092/79601804-4344ec80-809e-11ea-8a7a-057a95f41f52.jpg)

**Comment by eidetyler** [comment]
@CaityHeath Updated! 

https://www.dropbox.com/s/gvochis6hccx7h2/G_ModernShed_TheDifference_A.jpg?dl=0
