### ISSUE TITLE
Feature: desktop: wide screen

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#168]
When the site is stretched to over 21" (in know this will depend on several other factors) a large area of orange with the wordmark and the © info slides out from the right hand frame

![MSWEBQA-14](https://user-images.githubusercontent.com/63302981/79154878-27330980-7d85-11ea-848a-ee896ff7a3a1.jpg)

**Comment by CaityHeath** [comment]
Note to Caity: Breaks at 2665px
