### ISSUE TITLE
Bug: Featured sheds: Android phone: Edge and Chrome browser

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#170]
When pressing/clicking on a "featured" shed, nothing happens (no other photos appear as on desktop). The same on Android tablet with Chrome. If this is on purpose, Then the main photos have to change to more descriptive photos.

**Comment by ckillorin** [comment]
@ModernShed This is intentional on mobile + tablet. We can change the main photo for one of the others in the pop-out carousel. Just let us know which one you'd rather lead with!

**Comment by ModernShed** [comment]
Change the last one.. instead of the rear of the shed, show one of the interior.

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com
