### ISSUE TITLE
Content: Process: Order/Install/ photo labels (timelines)

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#171]
Please remove the timeline label/captions the images for "Order" and "Install" 
The timelines are just too flexible in so many different scenarios that it is best to keep that information between the rep and the customer.

**Comment by ckillorin** [comment]
@ModernShed the way this section is designed is to give a rough idea of timeline so they're well-educated prior to reaching out. All kinda focused on our primary goal of more qualified leads for your awesome sales team. Is it possible to assign a more broad range instead of removing the time estimate altogether? 

My only concern with removing it is it will create gaps in the grid and we lose the opportunity to give customers a broad sense of how long each phase could take.

**Comment by ModernShed** [comment]
Hmmm. This is difficult because it is based on the size of the structure.

Step 01 Design: small studios, a couple of days. Large sheds, a couple of weeks.

Step 02 Order: small studios, 3-5 days. Larger sheds, 2-4 weeks.

Step 03 Fabrication: small studios, 3-5 weeks. Larger sheds, 4-6 weeks.

Step 04 Install: small studios, 3-5 days. Larger sheds, 1-2 weeks.

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by ckillorin** [comment]
@eidetyler How does having a couple different time ranges work with the design? 

Alternately, we could be even more broad and simply state the whole range, "3 days to 6 weeks"

Thoughts?

**Comment by ModernShed** [comment]
I know you are trying to use as few characters as possible... But I don't want folks to be scared off and at the same time hold us to something.


How about Step 01 Design  3-5 days, Step 02 Order 5-7 days Step 03 Fabrication 4-6 weeks and Install 3-7 days. Can we put an asterisk with it stating these are approximate times for small studios and larger structures are longer 




Tim Vack


General Manager Modern-Shed, Inc


206-524-1188 ext. 700


tim@modern-shed.com






Outlook for Android







On Tue, Apr 14, 2020 at 2:48 PM -0700, "ckillorin" <notifications@github.com> wrote:















@eidetyler How does having a couple different time ranges work with the design?


Alternately, we could be even more broad and simply state the whole range, "3 days to 6 weeks"


Thoughts?

**Comment by ckillorin** [comment]
This is a good solve! @eidetyler?

**Comment by eidetyler** [comment]
@CaityHeath - Lets asterisk those timelines that @ModernShed Tim gave us, and we can add this to the end of the page. 

![Screen Shot 2020-04-15 at 10 24 18 AM](https://user-images.githubusercontent.com/60489677/79367917-78690780-7f03-11ea-8ffa-b36ef626a758.png)
