### ISSUE TITLE
Home - Featured Shed Meta Data Missing

### ISSUE THREAD

**Issue by ckillorin** [designbyparker/ModernShed#173]
@ModernShed 

we need you to provide the following information for all of the featured sheds:

- Use

- Sq Footage

- City, State

**Comment by ModernShed** [comment]
Upper left: Guest Studio | 180 sf | Puget Sound

Upper right: Home Office | 120 sf | Oregon

Lower left: Dwelling Compound | 640 sf, 280 sf, 100 sf | Port Townsend

Lower right: Office | 140 sf | Oregon

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by CaityHeath** [comment]
This data has been sent to Monte for database updates.
