### ISSUE TITLE
Logo Contrast Issue on Home Page

### ISSUE THREAD

**Issue by ckillorin** [designbyparker/ModernShed#28]
One of the images in the hero carousel has a really light sky and you lose the logo. Not sure if it's worth retouching the sky or not. 
![Screen Shot 2020-03-26 at 1 35 29 PM](https://user-images.githubusercontent.com/60364092/77694240-f0788900-6f66-11ea-80ba-9fd7c7561f05.png)

**Comment by eidetyler** [comment]
This is totally blown out, so I could try and re-edit the image but It'll make the whole thing wonky looking. @CaityHeath - would it be possibile  to throw a transparency over all the header image section? Like 8% black transparency? Or would that slow things down a lot?

**Comment by eidetyler** [comment]
Should be updated "A" inside the Home page.
