### ISSUE TITLE
Sheds: Copy missing - Windows

### ISSUE THREAD

**Issue by ckillorin** [designbyparker/ModernShed#33]
In the approved design, this section had no copy. Looks like it's been redesigned to mirror the materials content module. 

Need to either remove these copy sections or have Britt write to them. Not sure how much we'd have to say about differently sized windows.
![Screen Shot 2020-03-26 at 1 56 12 PM](https://user-images.githubusercontent.com/60364092/77695902-be1c5b00-6f69-11ea-9803-27c5e89906e7.png)

Chrome/desktop

**Comment by eidetyler** [comment]
Let's get Brittany to write. I don't want Caity to have to adjust it at this point.

**Comment by ckillorin** [comment]
I flagged to Britt. Will let you know if she needs more direction about what we'd like to say about each size (there isn't a ton of detail to go off based on a review of whats on their site and in their catalogue)

Do we need to have copy here?

**Comment by ckillorin** [comment]
@CaityHeath we have updated copy for these. I'll tag you in the spreadsheet but also copying it all here:

Small

In a multitude of shapes, our small-option windows come in both casement, double-casement, and awning styles.

Tall

Our tall scaled windows are easy to customize. Choose between sliding glass, a fixed window over an awning, or an awning over fixed.

Full

Let the outdoors in. Our full-sized windows reach up to 60” x 72”.
