### ISSUE TITLE
Footer - LinkedIn + Facebook missing

### ISSUE THREAD

**Issue by ckillorin** [designbyparker/ModernShed#53]
unless this was intentional

chrome/mobile

**Comment by ckillorin** [comment]
![IMG_DD616CC23654-1](https://user-images.githubusercontent.com/60364092/77699466-b8297880-6f6f-11ea-9736-1770504e71dc.jpeg)

**Comment by eidetyler** [comment]
I think this just needs to be added to the build, No?
