### ISSUE TITLE
Contact - Interest copy is different on mobile

### ISSUE THREAD

**Issue by ckillorin** [designbyparker/ModernShed#54]
assuming this was intentional but mobile copy is way friendlier (and i prefer it)
![IMG_A0FB7BFC16BC-1](https://user-images.githubusercontent.com/60364092/77699783-43a30980-6f70-11ea-8ccc-52639e3598e3.jpeg)

**Comment by eidetyler** [comment]
I'd be fine just making these same changes on Desktop... Should we just go ahead and do that? @CaityHeath
